<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="EmployeesData">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Employee" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="EmpID" type="xs:integer"/>
              <xs:element name="EmpName" type="xs:string"/>
              <xs:element name="EmpDOB" type="xs:string"/>
              <xs:element name="EmpAddr" type="xs:string"/>
              <xs:element name="EmpSalryMonth" type="xs:string"/>
              <xs:element name="EmpSalary" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
