<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Orders">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="Order" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            
                            <xs:element name="OrderID" type="xs:string"/>
                            
                            <xs:element name="Items">
                                <xs:complexType>
                                    <xs:sequence>
                                        
                                        <xs:element name="Item" maxOccurs="unbounded" minOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Product" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>